# Generated by Django 2.0 on 2023-02-28 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaid', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summaryid', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('filetype', models.CharField(max_length=50)),
                ('udate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlpapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='upload',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlpapp.user'),
        ),
        migrations.AddField(
            model_name='summary',
            name='DOCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlpapp.upload'),
        ),
        migrations.AddField(
            model_name='question',
            name='DOCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlpapp.upload'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlpapp.user'),
        ),
    ]
