# Generated by Django 2.0 on 2023-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpapp', '0002_auto_20230307_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='filetype',
            field=models.CharField(max_length=500),
        ),
    ]
