# Generated by Django 2.0 on 2023-04-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpapp', '0005_auto_20230427_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(max_length=500),
        ),
    ]
