from django.urls import path
from nlpapp import views

urlpatterns = [
    path('home/',views.home),
    path('login/', views.loginfun),
    path('login_post/',views.login_post),
    path('adminviewusers/',views.adminviewusers),
    path('userregister/', views.userregister),
    path('userregister_post/',views.userregister_post),
    path('userviewprofile/',views.userviewprofile),
    path('editprofile/',views.editprofile),
    path('editprofile_post/',views.editprofile_post),
    path('useruploadtext/',views.useruploadtext),
    path('useruploadtext_post/',views.useruploadtext_post),
    path('useruploaddocument/', views.useruploaddocument),
    path('useruploaddocument_post/', views.useruploaddocument_post),
    path('useruploadvoice/', views.useruploadvoice),
    path('useruploadvoice_post/', views.useruploadvoice_post),
    path('userwiki/', views.userwiki),
    path('usersummary/', views.usersummary),
    path('userqa/', views.userqa),
    path('index/', views.index),
    path('signupindex/',views.signupindex),
    path('regusers/',views.regusers),
    path('userviewprofile1/',views.userviewprofile),
    path('uploaddocument/',views.uploaddocument),
    path('uploaddocument_post/', views.uploaddocument_post),
    path('dashboard/',views.dashboard),
    path('dashboard1/', views.dashboard1),
    path('uploadtext1/', views.uploadtext1),
    path('uploadtext1_post/', views.uploadtext1),
    path('uploadvoice1/', views.uploadvoice1),
    path('uploadvoice1_post/', views.uploadvoice1),
    path('extractedtext/',views.extractedtext),
    path('keywordandwiki1/', views.keywordandwiki1),
    path('summary1/', views.summary1),
    path('qa1/',views.qa1),
    path('extractedtext1/',views.extractedtext1),
    path('generatepdf/',views.generatepdf),
    path('generatedocument/',views.generatedocument),
    path('generatevoice/',views.generatevoice),
    path('generatepdf1/',views.generatepdf1),
    path('generatedocument1/',views.generatedocument1),
    path('generatevoice1/',views.generatevoice1),
    path('generatepdf2/',views.generatepdf2),
    path('generatedocument2/',views.generatedocument2),
    path('generatevoice2/',views.generatevoice2),

    # path('generatevoice/', views.generatevoice),
    # path('generatevoice/', views.generatevoice),

    # path('first/',views.first),

    path('input/', views.noteinput),

    # path('adminviewcomplaint/', views.adminviewcomplaint),
    # path('adminsendreply/', views.adminsendreply),
    # path('adminsendreply_post/',views.adminsendreply_post),
    path('sendcomplaint/', views.sendcomplaint),
    path('sendcomplaint_post/', views.sendcomplaint_post),
    path ('viewcomplaint/', views.viewcomplaint),
    path('search_post/', views.search_post),
    path('success2/', views.success2),
    path('sendreply/<cid>', views.sendreply),
    path('sendreply_post/', views.sendreply_post),
    path('viewreply/', views.viewreply)


]