# Generated by Django 2.0 on 2023-03-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlpapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='DOCID',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='DOCID',
        ),
        migrations.DeleteModel(
            name='question',
        ),
        migrations.DeleteModel(
            name='summary',
        ),
    ]
