# Generated by Django 2.0 on 2023-04-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpapp', '0004_remove_upload_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(max_length=500),
        ),
    ]
