# Generated by Django 2.0 on 2023-05-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlpapp', '0006_auto_20230427_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='USERID',
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
