# Generated by Django 2.0 on 2023-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpapp', '0007_auto_20230504_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(max_length=500),
        ),
    ]
